$login ="/login.php";
$validate_otp = "/pages/login/validate_otp.php";
$generate_otp = "/pages/login/generate_otp.php";
$contact_and_basic_info = "/pages/contact_and_basic_info/contact_and_basic_info.php";
$contact_and_basic_info_save = "/pages/contact_and_basic_info/contact_and_basic_info_save.php";
$general_history = "/pages/general_history/general_history.php";
$analytics = "/pages/analytics/analytics.php";
$general_history_save = "/pages/general_history/general_history_save.php"
$medical_status ="/pages/medical_status/medical_status.php";
$medical_status_save ="/pages/medical_status/medical_status_save.php";
$settings ="/pages/settings/settings.php";
$my_message ="/pages/my_message/my_message.php";
$notifications ="/pages/notifications/notifications.php";
$search ="/common/search.php";
$delete_cookie ="/common/delete_cookie.php";
$death_report_save = "/pages/death_report/death_report_save.php";